name: 部署 JSON 转换工具到 GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 调试 - 列出文件
        run: ls -la

      - name: 设置 Pages
        uses: actions/configure-pages@v5

      - name: 构建页面目录
        run: |
          mkdir -p _site
          cp jsonToExcel.html _site/index.html
          cp jsonToExcel.html _site/
          ls -la _site

      - name: 上传 Pages 工件
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
